# Generated by Django 2.2.2 on 2019-07-02 18:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('0', 'Current Affairs'), ('1', 'Politics'), ('3', 'Culture'), ('2', 'Sports')], default='1', max_length=100)),
                ('view', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('title_intro', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
