# Generated by Django 2.2.3 on 2019-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_id', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=400)),
                ('ip', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
